server:
  servlet:
    context-path: /
  port: 8080

auth:
  url: ${AUTH_URL:http://auth:8082/auth}

spring:
  application:
    name: group
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
#    properties:
#      hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: true

