server:
  servlet:
    context-path: /v1/group
  port: 8080

auth:
  url: ${AUTH_URL:http://auth:8080/auth}

spring:
  application:
    name: group
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

  jpa:
#    properties:
#      hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: true
logging:
  level:
    org: DEBUG
