apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tripapp-gateway
  # annotations:
  #   ingress.kubernetes.io/rewrite-target: /tripapp-ui
spec:
  rules:
    - host: "mastercc.hpc4ai.unito.it"
      http:
        paths:
          - pathType: Prefix
            path: /tripapp/banana
            backend:
              service:
                name: banana-service
                port:
                  number: 5678
          - pathType: Prefix
            path: /tripapp/apple
            backend:
              service:
                name: apple-service
                port:
                  number: 5678

          - pathType: Prefix
            path: /tripapp/ui
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
