server:
  port: 8080
  servlet:
    context-path: /v1/auth
spring:
  application:
    name: auth
  data:
    mongodb:
      host: ${DB_SERVER}
      port: ${DB_PORT}
      database: ${DB_NAME}
logging:
  level:
    org: DEBUG
