server:
  port: 8080
  servlet:
    context-path: /v1/auth
spring:
  application:
    name: auth
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_SERVER}:${DB_PORT}/${DB_NAME}?authSource=admin
logging:
  level:
    org: DEBUG
