server:
  port: 8080

auth:
  url: ${AUTH_URL}

zuul:
  add-proxy-headers: false
#  sensitive-headers:
  prefix: /api/gateway
  routes:
    # Auth is a intranet service, so we can use the internal DNS name
#    auth:
#      path: "/v*/auth/**"
#      url: ${AUTH_URL}
#      stripPrefix: true

    group:
      path: "/v*/group/**"
      url: ${GROUP_URL}
      stripPrefix: false

    # Core services
    wallet:
      path: "/v*/wallet/**"
      url: ${WALLET_URL}
      stripPrefix: false

    info:
      path: "/v*/infos/**"
      url: ${INFO_URL}
      stripPrefix: false

#    map:
#      path: "/v*/map/**"
#      url: ${MAP_URL}
#      stripPrefix: true
#
#    poll:
#      path: "/v*/poll/**"
#      url: ${POLL_URL}
#      stripPrefix: true
logging:
  level:
    org: DEBUG
