server:
  servlet:
    context-path: /v1/wallet
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org: DEBUG
