version: '3.8'
services:
  gateway:
    build: .
    container_name: tripapp-gateway
    environment:
      - SERVER_PROVA=http://echo-server:5678
#      - DB_SERVER=mongo
#      - DB_NAME=auth
      #      - DB_USER=tripapp
      #      - DB_PASSWORD=tripapp
#      - DB_PORT=27017
#    depends_on:
#      - mongo
    ports:
      - "8080:8080"
    networks:
      - tripapp-net

  echo-server:
    image: "hashicorp/http-echo"
    container_name: echo-server
    command: ["-text", "Hello World"]
    ports:
      - "5678:5678"
    networks:
      - tripapp-net

#volumes:
#  kanban-data:
networks:
  tripapp-net:
    name: tripapp-net
    driver: bridge