version: '3'
services:

  postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
#    volumes:
#      - kanban-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - kambannet
    environment:
      - POSTGRES_DB=group
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban

  user:
    build: .
    container_name: user
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=group
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 8082:8082
    depends_on:
      - postgres
    networks:
      - kambannet

#volumes:
#  kanban-data:
networks:
  kambannet:
    driver: bridge
