name: Deploy frontend docker image

env:
  IMAGE_NAME: ${{ github.repository }}-ui
  ACTOR: ${{ github.actor }}

on:
  push:
    branches: [ main, master, feat(infra)/infra-template ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: ASzc/change-string-case-action@v2
        id: string
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: tripapp-ui/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.string.outputs.lowercase }}:latest